using Win11PerformanceControlCenter.App.Models;

namespace Win11PerformanceControlCenter.App.Core;

public sealed class ActionCatalog
{
    private readonly IReadOnlyDictionary<string, ActionDefinition> _actions;

    public ActionCatalog()
    {
        var actions = new[]
        {
            new ActionDefinition("system.actionplan.preview", "Construir plan de acción",
                "Combina señales rápidas del equipo y propone qué revisar o ejecutar, sin aplicar cambios automáticamente.", ActionCategory.System, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("system.healthscore.analyze", "Health Score y baseline",
                "Captura una línea base local, calcula un score explicable y muestra los factores que descuentan puntos.", ActionCategory.System, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("system.changes.analyze", "Qué cambió",
                "Compara las dos últimas líneas base y muestra solo cambios materiales de salud, memoria, discos, red y estados.", ActionCategory.System, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("system.workload.status", "Estado PC en uso",
                "Indica si las tareas pesadas están permitidas según modo, inactividad y presión de D:.", ActionCategory.System, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("system.workload.inuse", "Proteger PC en uso",
                "Fuerza modo PC EN USO: bloquea tareas pesadas o disruptivas hasta cambiar el modo.", ActionCategory.System, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, true, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita")]),
            new ActionDefinition("system.workload.auto", "Volver a modo automático",
                "Permite que la app decida si puede hacer mantenimiento según el tiempo de inactividad.", ActionCategory.System, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, true, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita")]),
            new ActionDefinition("system.workload.maintenance", "Permitir mantenimiento",
                "Habilita tareas pesadas de forma explícita. D: por debajo del 3% sigue bloqueando operaciones pesadas.", ActionCategory.System, ActionRisk.CAUTION, false, ConnectivityRequirement.OFFLINE, true, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita")]),
            new ActionDefinition("system.health.scan", "Diagnóstico del sistema",
                "Obtiene una línea base segura del equipo.", ActionCategory.System, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("system.integrity.check", "Comprobar integridad de Windows",
                "Ejecuta DISM /CheckHealth en modo lectura; requiere elevación puntual.", ActionCategory.System, ActionRisk.SAFE, true, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("system.integrity.repair", "Reparar integridad de Windows",
                "Con UAC: ejecuta DISM /RestoreHealth y SFC /scannow, después verifica el resultado.", ActionCategory.System, ActionRisk.CAUTION, true, ConnectivityRequirement.OPTIONAL_ONLINE, false, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita antes de reparar Windows")]),
            new ActionDefinition("system.reliability.analyze", "Reliability Analyzer",
                "Correlaciona reinicios, apagados y eventos críticos.", ActionCategory.Reliability, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("system.crash.analyze", "Crash Intelligence",
                "Agrupa fallos, hangs, WHEA y apagados no limpios y enlaza cada patrón con un diagnóstico concreto sin inventar causas.", ActionCategory.Reliability, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("memory.analyze", "Analizar memoria",
                "Mide RAM física, disponible y presión general.", ActionCategory.Memory, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("processes.hygiene.analyze", "Process Hygiene",
                "Detecta residuos de laboratorio como Edge headless SIG, emuladores Android de prueba y Uvicorn huérfanos; protege bots y automatizaciones.", ActionCategory.Memory, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.DRY_RUN),
            new ActionDefinition("processes.hygiene.stop", "Detener residuo seleccionado",
                "Detiene únicamente un residuo clasificado por Process Hygiene si PID, huella y clasificación siguen coincidiendo; nunca acepta un PID arbitrario.", ActionCategory.Memory, ActionRisk.CAUTION, false, ConnectivityRequirement.OFFLINE, false, ActionMode.WRITE,
                [new ActionParameterDefinition("processId", ActionParameterType.INTEGER, true, "PID exacto obtenido de la previsualización"), new ActionParameterDefinition("fingerprint", ActionParameterType.STRING, true, "Huella efímera obtenida de la previsualización"), new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita")]),
            new ActionDefinition("memory.trim.preview", "Previsualizar MemoryTrim",
                "Identifica procesos con working set alto sin modificar memoria.", ActionCategory.Memory, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.DRY_RUN),
            new ActionDefinition("memory.trim", "MemoryTrim seleccionado",
                "Recorta working sets sólo de procesos seleccionados y elegibles; el efecto es transitorio.", ActionCategory.Memory, ActionRisk.CAUTION, false, ConnectivityRequirement.OFFLINE, false, ActionMode.WRITE,
                [new ActionParameterDefinition("processIds", ActionParameterType.INTEGER_ARRAY, true, "PIDs seleccionados desde la previsualización"), new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita de la operación")]),
            new ActionDefinition("memory.pagefile.analyze", "Analizar archivo de paginación",
                "Lee configuración y uso actual del pagefile sin modificarlo.", ActionCategory.Memory, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("memory.pagefile.capped", "Aplicar pagefile 4–8 GB en D:",
                "Con UAC: mantiene 512 MB en C: y configura D: con 4 GB inicial / 8 GB máximo. Guarda rollback y nunca supera 10 GB.", ActionCategory.Memory, ActionRisk.CAUTION, true, ConnectivityRequirement.OFFLINE, true, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita")]),
            new ActionDefinition("memory.pagefile.restore", "Restaurar configuración de pagefile",
                "Con UAC: restaura la administración automática/manual y PagingFiles capturados antes del cambio.", ActionCategory.Memory, ActionRisk.SAFE, true, ConnectivityRequirement.OFFLINE, false, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita del rollback")]),
            new ActionDefinition("cpu.ecoqos.analyze", "Analizar EcoQoS",
                "Detecta candidatos sin aplicar cambios.", ActionCategory.CPU, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("cpu.ecoqos.apply", "Aplicar EcoQoS seleccionado",
                "Aplica ExecutionSpeed throttling sólo a procesos seleccionados y elegibles.", ActionCategory.CPU, ActionRisk.CAUTION, false, ConnectivityRequirement.OFFLINE, true, ActionMode.WRITE,
                [new ActionParameterDefinition("processIds", ActionParameterType.INTEGER_ARRAY, true, "PIDs seleccionados desde el análisis"), new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita de la operación")]),
            new ActionDefinition("cpu.ecoqos.restore", "Restaurar EcoQoS",
                "Restaura el estado previo registrado para procesos seleccionados.", ActionCategory.CPU, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, true, ActionMode.WRITE,
                [new ActionParameterDefinition("processIds", ActionParameterType.INTEGER_ARRAY, true, "PIDs previamente modificados por la app"), new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita del rollback")]),
            new ActionDefinition("disk.scan", "Analizar almacenamiento",
                "Mide espacio y temporales regenerables.", ActionCategory.Storage, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("disk.cleanup.safe", "Limpieza segura",
                "Previsualiza la limpieza; no borra archivos en esta fase.", ActionCategory.Storage, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, true, ActionMode.DRY_RUN),
            new ActionDefinition("disk.cleanup.execute", "Eliminar cachés regenerables",
                "Requiere previsualización y confirmación. Solo limpia archivos antiguos de rutas permitidas, nunca extensiones instaladas, perfiles, sesiones ni documentos.", ActionCategory.Storage, ActionRisk.CAUTION, false, ConnectivityRequirement.OFFLINE, false, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita tras previsualización")]),
            new ActionDefinition("disk.appdata.rank", "Ranking de AppData Local",
                "Mide las mayores carpetas sin borrar nada ni inferir que sean residuos.", ActionCategory.Storage, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("disk.volumes.audit", "Auditar C: / D: y volúmenes",
                "Mide espacio total/libre y clasifica presión de almacenamiento en todos los volúmenes fijos.", ActionCategory.Storage, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("disk.storage.watch", "Storage Watch",
                "Compara espacio libre contra el baseline anterior y detecta crecimiento anormal sin borrar archivos.", ActionCategory.Storage, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("disk.hotspots.scan", "Buscar hotspots de disco",
                "Escaneo read-only acotado por tiempo en volúmenes con poco espacio; los tamaños parciales se marcan como tales.", ActionCategory.Storage, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("disk.hibernate.status", "Estado de hibernación",
                "Consulta los estados de suspensión e inicio rápido, sin cambios.", ActionCategory.Storage, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("disk.hibernate.reduce", "Hibernación reducida",
                "Con UAC: reduce hiberfil.sys, conserva Inicio rápido pero DESHABILITA la hibernación completa.", ActionCategory.Storage, ActionRisk.CAUTION, true, ConnectivityRequirement.OFFLINE, false, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita")]),
            new ActionDefinition("network.test", "Analizar red",
                "Mide el adaptador activo sin cambiar su configuración.", ActionCategory.Network, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("network.flushdns", "Vaciar caché DNS",
                "Con UAC: vacía únicamente la caché del resolvedor DNS de Windows.", ActionCategory.Network, ActionRisk.SAFE, true, ConnectivityRequirement.OFFLINE, false, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita")]),
            new ActionDefinition("network.winsock.reset", "Restablecer Winsock",
                "Con UAC: restablece el catálogo Winsock. Puede requerir reinicio y no se aplica automáticamente.", ActionCategory.Network, ActionRisk.EXPLICIT_CONFIRMATION, true, ConnectivityRequirement.OFFLINE, false, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita del reset de red")]),
            new ActionDefinition("drivers.analyze", "Analizar drivers",
                "Detecta dispositivos con códigos de problema mediante WMI.", ActionCategory.Drivers, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("drivers.rescan", "Reescanear hardware",
                "Con UAC: pide a Plug and Play que vuelva a detectar dispositivos; no instala drivers de fuentes externas.", ActionCategory.Drivers, ActionRisk.SAFE, true, ConnectivityRequirement.OFFLINE, false, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita")]),
            new ActionDefinition("drivers.usb.analyze", "USB Repair Center",
                "Enumera dispositivos USB, códigos de problema y cuáles son elegibles para un reinicio controlado.", ActionCategory.Drivers, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("drivers.usb.restart", "Reiniciar dispositivo USB",
                "Con UAC: reinicia solo el dispositivo USB seleccionado si pasa la política de protección y verifica su estado después.", ActionCategory.Drivers, ActionRisk.CAUTION, true, ConnectivityRequirement.OFFLINE, false, ActionMode.WRITE,
                [new ActionParameterDefinition("deviceInstanceId", ActionParameterType.STRING, true, "Instance ID exacto obtenido del análisis"), new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita")]),
            new ActionDefinition("system.activation.analyze", "Comprobar activación",
                "Lee el estado de licencia de Windows sin modificarlo.", ActionCategory.System, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("system.registry.evidence", "Evidencia Registry",
                "Audita puntos sensibles documentados como AppInit, IFEO y Winlogon. No limpia ni borra el registro.", ActionCategory.System, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("system.com.evidence", "Evidencia COM",
                "Escaneo bounded y read-only de CLSID con servidores locales ausentes. Nunca elimina registros COM.", ActionCategory.System, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("system.certificates.audit", "Auditar certificados personales",
                "Lee certificados personales próximos a vencer, vencidos o aún no válidos; nunca elimina certificados.", ActionCategory.System, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("browsers.inventory", "Inventario de navegadores",
                "Detecta navegadores y perfiles locales sin abrirlos ni modificarlos.", ActionCategory.Browsers, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("browsers.edge.performance.audit", "Edge Performance",
                "Mide procesos y memoria de Edge y revisa background mode, Startup Boost, Sleeping Tabs, Efficiency Mode y autoarranque sin modificar perfiles.", ActionCategory.Browsers, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("browsers.edge.performance.optimize", "Optimizar Edge",
                "Aplica un perfil reversible mediante políticas de usuario: sin background, sin Startup Boost, Sleeping Tabs a 5 min, auto-discard, Efficiency Mode y sin autoarranque visible. No cierra Edge ni toca sesiones/extensiones.", ActionCategory.Browsers, ActionRisk.CAUTION, false, ConnectivityRequirement.OFFLINE, true, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita")]),
            new ActionDefinition("browsers.edge.performance.restore", "Restaurar configuración Edge",
                "Restaura exactamente las políticas y entradas de autoarranque capturadas antes de Optimizar Edge.", ActionCategory.Browsers, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita del rollback")]),
            new ActionDefinition("browsers.extensions.health", "Integridad de extensiones Edge",
                "Explica qué está bien, qué son residuos y qué requiere reparación. No modifica el perfil.", ActionCategory.Browsers, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("browsers.extensions.orphans.preview", "Revisar residuos de extensiones",
                "Previsualiza datos de extensiones ya desinstaladas. No están ejecutándose y la revisión no modifica Edge.", ActionCategory.Browsers, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("browsers.extensions.orphans.quarantine", "Poner residuos en cuarentena",
                "Con Edge cerrado, mueve únicamente datos huérfanos de Local Extension Settings a una cuarentena reversible.", ActionCategory.Browsers, ActionRisk.CAUTION, false, ConnectivityRequirement.OFFLINE, true, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita después de revisar los residuos")]),
            new ActionDefinition("browsers.extensions.orphans.restore", "Restaurar última cuarentena Edge",
                "Con Edge cerrado, devuelve a su ubicación original el último lote puesto en cuarentena por la app.", ActionCategory.Browsers, ActionRisk.CAUTION, false, ConnectivityRequirement.OFFLINE, false, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita del rollback")]),
            new ActionDefinition("multimedia.inventory", "Inventario multimedia",
                "Enumera dispositivos de audio y vídeo registrados por Windows.", ActionCategory.Multimedia, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("multimedia.audio.restart", "Reiniciar audio de Windows",
                "Con UAC: reinicia el servicio Windows Audio y vuelve a verificar dispositivos.", ActionCategory.Multimedia, ActionRisk.CAUTION, true, ConnectivityRequirement.OFFLINE, false, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación: el audio se interrumpirá unos segundos")]),
            new ActionDefinition("startup.audit", "Auditar inicio y servicios",
                "Enumera startup commands y servicios automáticos sin modificarlos.", ActionCategory.Startup, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("startup.services.preview", "Revisar servicios automáticos",
                "Clasifica servicios automáticos en protegidos o revisables; incluye dependencias y no modifica ninguno.", ActionCategory.Startup, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("startup.service.dependencies", "Ver dependencias de servicio",
                "Enumera servicios dependientes del servicio seleccionado; es read-only y se usa como barrera antes de cambios.", ActionCategory.Startup, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ,
                [new ActionParameterDefinition("serviceName", ActionParameterType.STRING, true, "Nombre exacto obtenido del análisis")]),
            new ActionDefinition("startup.service.setmode", "Cambiar inicio de servicio",
                "Con UAC: cambia a Manual o Disabled solo un servicio de terceros revisable y guarda rollback.", ActionCategory.Startup, ActionRisk.CAUTION, true, ConnectivityRequirement.OFFLINE, true, ActionMode.WRITE,
                [new ActionParameterDefinition("serviceName", ActionParameterType.STRING, true, "Nombre exacto obtenido del análisis"), new ActionParameterDefinition("targetMode", ActionParameterType.STRING, true, "Manual o Disabled"), new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita")]),
            new ActionDefinition("startup.service.restore", "Restaurar inicio de servicio",
                "Con UAC: restaura el StartMode guardado por la app para un servicio previamente modificado.", ActionCategory.Startup, ActionRisk.SAFE, true, ConnectivityRequirement.OFFLINE, false, ActionMode.WRITE,
                [new ActionParameterDefinition("serviceName", ActionParameterType.STRING, true, "Nombre exacto con snapshot"), new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita del rollback")]),
            new ActionDefinition("startup.entries.preview", "Revisar autoarranque Run/RunOnce",
                "Clasifica entradas de autoarranque en protegidas, revisables y deshabilitadas por la app.", ActionCategory.Startup, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("startup.entry.disable", "Deshabilitar entrada de autoarranque",
                "Con UAC: elimina solo la entrada Run/RunOnce seleccionada, guarda snapshot y no cierra el proceso actual.", ActionCategory.Startup, ActionRisk.CAUTION, true, ConnectivityRequirement.OFFLINE, true, ActionMode.WRITE,
                [new ActionParameterDefinition("entryId", ActionParameterType.STRING, true, "ID exacto obtenido de la previsualización"), new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita")]),
            new ActionDefinition("startup.entry.restore", "Restaurar entrada de autoarranque",
                "Con UAC: restaura exactamente una entrada Run/RunOnce deshabilitada previamente por la app.", ActionCategory.Startup, ActionRisk.SAFE, true, ConnectivityRequirement.OFFLINE, false, ActionMode.WRITE,
                [new ActionParameterDefinition("entryId", ActionParameterType.STRING, true, "ID exacto con snapshot"), new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita del rollback")]),
            new ActionDefinition("startup.tasks.preview", "Revisar tareas programadas",
                "Clasifica tareas protegidas/revisables y detecta COM handlers stale. Microsoft, Windows, seguridad y automatización sensible fallan cerradas.", ActionCategory.Startup, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("startup.task.disable", "Deshabilitar tarea programada",
                "Con UAC: deshabilita solo la tarea seleccionada, guarda snapshot y no termina procesos ya iniciados.", ActionCategory.Startup, ActionRisk.CAUTION, true, ConnectivityRequirement.OFFLINE, true, ActionMode.WRITE,
                [new ActionParameterDefinition("entryId", ActionParameterType.STRING, true, "ID exacto obtenido de la previsualización"), new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita")]),
            new ActionDefinition("startup.task.restore", "Restaurar tarea programada",
                "Con UAC: vuelve a habilitar exactamente una tarea deshabilitada previamente por la app y verifica el estado.", ActionCategory.Startup, ActionRisk.SAFE, true, ConnectivityRequirement.OFFLINE, false, ActionMode.WRITE,
                [new ActionParameterDefinition("entryId", ActionParameterType.STRING, true, "ID exacto con snapshot"), new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita del rollback")]),
            new ActionDefinition("windows.update.audit", "Auditar Windows Update",
                "Resume eventos recientes de instalación y fallo de Windows Update.", ActionCategory.WindowsUpdate, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("windows.update.services.restart", "Reiniciar servicios de Windows Update",
                "Con UAC: reinicia BITS y Windows Update; no borra SoftwareDistribution ni historial.", ActionCategory.WindowsUpdate, ActionRisk.CAUTION, true, ConnectivityRequirement.OFFLINE, false, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita")]),
            new ActionDefinition("apps.inventory", "Inventario de aplicaciones",
                "Enumera aplicaciones instaladas desde el registro sin desinstalar nada.", ActionCategory.Apps, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("privacy.audit", "Auditar privacidad",
                "Lee una selección documentada de configuraciones de privacidad sin juzgarlas ni modificarlas.", ActionCategory.Privacy, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("developer.audit", "Auditar developer tooling",
                "Detecta toolchains comunes y sus versiones desde PATH.", ActionCategory.Developer, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("lab.reliability.status", "Reliability Lab",
                "Verifica regresiones históricas y barreras de seguridad sin ejecutar escenarios destructivos sobre el Windows real.", ActionCategory.Developer, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("lab.outcomes.status", "Outcome coverage",
                "Audita qué acciones WRITE tienen post-check, rollback, efecto transitorio o reinicio pendiente y cruza evidencia del log.", ActionCategory.Developer, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("thermal.audit", "Auditar energía y temperaturas",
                "Lee el plan de energía activo y sensores ACPI disponibles.", ActionCategory.Thermal, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("thermal.power.balanced", "Usar plan Equilibrado",
                "Activa el plan Equilibrado y guarda el plan anterior para rollback.", ActionCategory.Thermal, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, true, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita")]),
            new ActionDefinition("thermal.power.performance", "Usar Alto rendimiento",
                "Activa Alto rendimiento; puede aumentar temperatura y consumo. Guarda rollback.", ActionCategory.Thermal, ActionRisk.CAUTION, false, ConnectivityRequirement.OFFLINE, true, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita")]),
            new ActionDefinition("thermal.power.restore", "Restaurar plan de energía",
                "Restaura el plan activo capturado antes del último cambio hecho por la app.", ActionCategory.Thermal, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita del rollback")]),
            new ActionDefinition("boot.audit", "Auditar arranque",
                "Lee eventos de Diagnostics-Performance del arranque.", ActionCategory.Boot, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("sleepresume.audit", "Auditar suspensión y reanudación",
                "Construye una timeline de eventos de sleep/resume.", ActionCategory.SleepResume, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("explorer.audit", "Auditar Explorer",
                "Mide memoria, threads, handles y respuesta de explorer.exe.", ActionCategory.Explorer, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("explorer.restart", "Reiniciar Explorer",
                "Reinicia explorer.exe y verifica que vuelva a responder. Las ventanas del Explorador pueden cerrarse.", ActionCategory.Explorer, ActionRisk.CAUTION, false, ConnectivityRequirement.OFFLINE, false, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita")]),
            new ActionDefinition("backup.status", "Estado de backup y rollback",
                "Detecta operaciones incompletas y snapshots de rollback mantenidos por la app.", ActionCategory.Backup, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("backup.rollback.center", "Rollback Center",
                "Reúne cambios reversibles de EcoQoS, servicios, tareas, pagefile, energía, autoarranque y Edge en una sola vista.", ActionCategory.Backup, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("diagnostics.bundle.create", "Crear bundle diagnóstico sanitizado",
                "Crea un ZIP local con diagnósticos y estado de la app, excluyendo comandos de autoarranque, argumentos de tareas, IDs PnP/USB, claves, cookies, sesiones y logs crudos.", ActionCategory.Backup, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita antes de crear el archivo local")]),
            new ActionDefinition("maintenance.policy.status", "Estado de automatización segura",
                "Muestra la política de mantenimiento read-only. Por defecto está OFF.", ActionCategory.System, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ),
            new ActionDefinition("maintenance.policy.readonly", "Activar mantenimiento read-only en reposo",
                "Habilita un lote fijo de diagnósticos solo cuando el equipo está inactivo o en MANTENIMIENTO. Nunca habilita WRITE.", ActionCategory.System, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, true, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita")]),
            new ActionDefinition("maintenance.policy.off", "Desactivar automatización",
                "Vuelve a OFF. Ningún lote de mantenimiento podrá ejecutarse mientras esté desactivado.", ActionCategory.System, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, true, ActionMode.WRITE,
                [new ActionParameterDefinition("confirmed", ActionParameterType.BOOLEAN, true, "Confirmación explícita")]),
            new ActionDefinition("maintenance.safe.run", "Ejecutar lote read-only",
                "Ejecuta el conjunto fijo de diagnósticos seguros si la política está habilitada y el PC no está en uso. No contiene acciones WRITE.", ActionCategory.System, ActionRisk.SAFE, false, ConnectivityRequirement.OFFLINE, false, ActionMode.READ)
        };

        _actions = actions.ToDictionary(action => action.Id, StringComparer.OrdinalIgnoreCase);
    }

    public IReadOnlyCollection<ActionDefinition> All => [.. _actions.Values];

    public ActionDefinition GetRequired(string id)
    {
        if (!_actions.TryGetValue(id, out var action))
            throw new InvalidOperationException("Action ID no permitida: " + id);
        return action;
    }
}
